### ISSUE TITLE
mencoder is not in Jessie

### ISSUE THREAD

**Issue by s-celles** [martinohanlon/pelmetcam#1]
Hi @martinohanlon ,

I'd like to tell you that, if you want to snowboard again in France with Raspberry Pi pelmetcam and an updated Raspbian you will need to find an alternative for `mencoder`.

https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=123442
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=741310

Kind regards

**Comment by martinohanlon** [comment]
Or any other country.

**Comment by s-celles** [comment]
yes of course ;-)

**Comment by s-celles** [comment]
`avconv` (from libav) might probably be used in `createVideos.sh` instead of `mencoder`
